async function loadJson(path){const r=await fetch(path);if(!r.ok)throw new Error(path);return r.json();}
const pct=(x,d=0)=>x==null?'—':`${(Number(x)*100).toFixed(d)}%`;
const num=(x,d=0)=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const money=x=>x==null?'—':`$${Number(x).toFixed(x<1?4:2)}`;
const seconds=x=>x==null?'—':`${Number(x).toFixed(Number(x)<10?1:0)}s`;
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const modelName=e=>[e.provider,e.model].filter(Boolean).join('/')+(e.reasoning_effort?` · ${e.reasoning_effort}`:'');
const routes=[['/','Home'],['/leaderboard','Results'],['/tasks','Tasks'],['/methodology','Method'],['/submit','Run']];
const taskStats={total:70,publicDev:55,anchor:5,fresh:5,privateTemplates:5,categories:['basic tool use','file operations','codebase navigation','bugfixes with tests','PR summary writing','GitHub issue triage','docs research','provider config','browser automation','CSV/data analysis','log analysis','security/CVE triage','Dockerfile optimization','CI/CD diagnosis','cron scheduling','context recovery','memory/privacy boundary','email/calendar fixtures','mock API workflow','false-done traps','marketing','SEO','technology RFPs','science synthesis','translation','legal','finance','health','trivia','academia']};
const suiteCards=[['public-dev','55','Local dev + smoke tasks. Deterministic, credential-free, public by design.'],['anchor','5','Stable longitudinal references for comparing drift over time.'],['fresh-rolling','5','Fresh waves intended to resist static prompt overfitting.'],['private-holdout','5','Public templates only; official packs remain maintainer controlled.']];
let state={leader:null,result:null,filter:'',suite:'',sort:'score',view:'cards'};
function sourceRows(leader){return (leader.official||[]).length||(leader.unofficial||[]).length?[...(leader.official||[]),...(leader.unofficial||[])]:[...(leader.entries||[])];}
function dedupe(rows){const seen=new Set();return rows.filter(e=>{const k=e.run_id||`${e.provider}/${e.model}/${e.suite}/${e.reasoning_effort}`;if(seen.has(k))return false;seen.add(k);return true;});}
function summaries(leader){if((leader.model_summaries||[]).length)return leader.model_summaries;return dedupe(sourceRows(leader)).map(e=>({...e,submission_count:1,best_score_percentage:e.score_percentage??e.overall_score,average_score_percentage:e.score_percentage??e.overall_score,best_submission_id:e.run_id}));}
function scoreOf(e){return e.score_percentage??e.overall_score??e.average_score_percentage??e.best_score_percentage??0;}
function rawOf(e){return e.raw_overall_score??e.raw_score_percentage??scoreOf(e);}
function filterSort(rows){const q=state.filter.toLowerCase();return rows.filter(e=>{const hay=[e.run_id,e.agent,e.provider,e.model,e.model_key,e.suite,e.reasoning_effort].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state.suite||e.suite===state.suite);}).sort((a,b)=>{if(state.sort==='false_done')return(a.false_done_rate??a.average_false_done_rate??1)-(b.false_done_rate??b.average_false_done_rate??1);if(state.sort==='time')return(a.total_execution_time_seconds??a.average_total_execution_time_seconds??Infinity)-(b.total_execution_time_seconds??b.average_total_execution_time_seconds??Infinity);if(state.sort==='tokens')return(a.total_tokens??a.average_total_tokens??Infinity)-(b.total_tokens??b.average_total_tokens??Infinity);if(state.sort==='raw')return rawOf(b)-rawOf(a);return scoreOf(b)-scoreOf(a);});}
function nav(){for(const id of ['desktop-nav','bottom-nav']){const el=document.getElementById(id);if(!el)return;el.innerHTML=routes.map(([href,label])=>`<a href="#${href}" data-route="${href}">${label}</a>`).join('');}}
function updateNav(path){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===path));}
function heroStats(leader){const rows=dedupe(sourceRows(leader));return `<div class="grid stats"><div class="stat"><b>${taskStats.total}</b><span>tasks/templates</span></div><div class="stat"><b>${taskStats.publicDev}</b><span>public-dev tasks</span></div><div class="stat"><b>${(leader.official||[]).length}</b><span>official runs</span></div><div class="stat"><b>${rows.length}</b><span>public samples</span></div></div>`;}
function resultCards(rows,limit=99){return `<div class="results-grid">${rows.slice(0,limit).map((s,i)=>{const model=[s.provider,s.model].filter(Boolean).join('/')||s.model_key||'unknown';const score=s.average_score_percentage??s.best_score_percentage??s.score_percentage??s.overall_score;const fd=s.average_false_done_rate??s.false_done_rate;const to=s.average_timeout_rate??s.timeout_rate;const time=s.average_total_execution_time_seconds??s.total_execution_time_seconds;const tokens=s.average_total_tokens??s.total_tokens;const tools=s.average_tool_call_count??s.tool_call_count;return `<article class="result-card"><div class="result-top"><div><div class="rank">${s.official?'OFFICIAL':'SAMPLE'} #${i+1}</div><div class="model">${esc(model)}</div><div class="small">${esc(s.agent||'agent')} · ${s.submission_count??1} run${(s.submission_count??1)===1?'':'s'} · ${esc(s.suite||'public-dev')}</div></div><span class="pill">${esc(s.reasoning_effort||'no reasoning')}</span></div><div class="scoreline"><span class="big">${pct(score)}</span><span class="small">score</span></div><div class="metrics"><div class="metric"><b>${pct(fd)}</b><span>false done</span></div><div class="metric"><b>${pct(to)}</b><span>timeout</span></div><div class="metric"><b>${seconds(time)}</b><span>task seconds</span></div><div class="metric"><b>${num(tokens)}</b><span>tokens</span></div><div class="metric"><b>${num(tools)}</b><span>tools</span></div><div class="metric"><b>${esc(s.best_submission_id||s.run_id||'—')}</b><span>best run</span></div></div></article>`;}).join('')}</div>`;}
function controls(){const suites=[...new Set(sourceRows(state.leader).map(e=>e.suite).filter(Boolean))].sort();return `<div class="controls"><div class="control"><label>Filter provider/model/agent</label><input id="f" type="search" value="${esc(state.filter)}" placeholder="openrouter, deepseek, gpt"></div><div class="control"><label>Suite</label><select id="s"><option value="">All suites</option>${suites.map(x=>`<option ${state.suite===x?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('')}</select></div><div class="control"><label>Sort</label><select id="sort">${[['score','Score'],['raw','Raw score'],['false_done','False-done'],['time','Task seconds'],['tokens','Tokens']].map(([v,l])=>`<option ${state.sort===v?'selected':''} value="${v}">${l}</option>`).join('')}</select></div></div>`;}
function runTable(rows){return `<div class="table-wrap ${state.view==='table'?'active':''}"><table><thead><tr><th>Run</th><th>Agent/model</th><th>Score</th><th>Raw</th><th>Pass@1</th><th>False done</th><th>Time</th><th>Tokens</th><th>Status</th></tr></thead><tbody>${rows.map(e=>`<tr><td><span class="mono">${esc(e.run_id)}</span><br><span class="small">${esc(e.suite)}</span></td><td><b>${esc(e.agent)}</b><br><span class="small">${esc(modelName(e))}</span></td><td>${pct(e.score_percentage??e.overall_score)}</td><td>${pct(e.raw_overall_score??e.raw_score_percentage)}</td><td>${pct(e.pass_at_1)}</td><td class="${e.false_done_rate?'bad':'good'}">${pct(e.false_done_rate)}</td><td>${seconds(e.total_execution_time_seconds)}</td><td>${num(e.total_tokens)}</td><td>${e.official?'Official':'Public-dev sample'}</td></tr>`).join('')}</tbody></table></div>`;}
function home(){const top=filterSort(summaries(state.leader)).slice(0,3);return `<section class="hero"><span class="eyebrow"><span class="dot"></span>Execution-based agent benchmark</span><h1>Stop rewarding agents for saying done.</h1><p class="lead">HermesBench measures whether tool-using agents actually inspect files, run commands, produce artifacts, pass checks, and leave auditable evidence.</p><div class="actions"><a class="btn primary" href="#/leaderboard">View results</a><a class="btn" href="#/submit">Run locally</a></div>${heroStats(state.leader)}<div class="notice"><b>No official rankings yet.</b> Public-dev runs are smoke samples. Official comparisons require maintainer-controlled private/fresh packs.</div></section><section class="section"><div class="section-head"><span class="pill">Current signal</span><h2>Top public-dev samples</h2><p class="muted">Cards first, tables later. Every score is paired with false-done, timeout, token, and provenance context.</p></div>${resultCards(top,3)}</section><section class="section split"><div class="card"><span class="pill">Why it exists</span><h2>Static benchmarks are benchmaxxed.</h2><p class="muted">Public prompts leak, harnesses become targets, and Q&A scores stop predicting whether an agent can finish messy real work. HermesBench splits public-dev, anchor, fresh, and private packs to keep development useful without making official scoring trivial to overfit.</p></div><div class="code"><code>uv run hermesbench validate-tasks\nuv run hermesbench run --agent mock --suite public-dev --output-dir /tmp/hermesbench-results\nuv run hermesbench score /tmp/hermesbench-results/*.json</code></div></section>`;}
function leaderboard(){const rows=filterSort(dedupe(sourceRows(state.leader)));return `<section class="section"><div class="section-head"><span class="pill">Results</span><h1>Leaderboard scaffold</h1><p class="lead">Unofficial public-dev samples are useful telemetry, not final rankings. Official rows will appear only after repeated maintainer runs on private/fresh packs.</p></div><div class="notice">${esc(state.leader.metric_notes||'Public-dev rows are single-run samples unless grouped by repeated runs.')}</div>${controls()}<div class="tabs"><button class="tab ${state.view==='cards'?'active':''}" data-view="cards">Cards</button><button class="tab ${state.view==='table'?'active':''}" data-view="table">Advanced table</button></div><div id="cards" style="display:${state.view==='cards'?'block':'none'};margin-top:12px">${resultCards(rows)}</div>${runTable(rows)}</section>`;}
function tasks(){return `<section class="section"><div class="section-head"><span class="pill">Task suites</span><h1>70 task specs, 55 runnable public-dev tasks.</h1><p class="lead">Tasks are Markdown + YAML packages with fixtures, expected artifacts, deterministic checks, hidden-check notes, freshness metadata, and cleanup rules.</p></div><div class="task-groups">${suiteCards.map(([id,count,txt])=>`<article class="task-card"><div class="rank">${esc(id)}</div><h3>${esc(count)} entries</h3><p class="muted">${esc(txt)}</p></article>`).join('')}</div><section class="section"><h2>Coverage</h2><div class="chips">${taskStats.categories.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div></section></section>`;}
function methodology(){return `<section class="section"><div class="section-head"><span class="pill">Methodology</span><h1>Execution first. Judges second.</h1><p class="lead">Objective tasks should be graded by artifacts, tests, commands, and deterministic checks. LLM judges are secondary only where objective scoring cannot capture quality.</p></div><div class="stack"><div class="card"><h2>Scoring integrity</h2><div class="metrics"><div class="metric"><b>False-done penalty</b><span>Claims without verification are measurable failures.</span></div><div class="metric"><b>Private/fresh split</b><span>Official runs need non-public packs.</span></div><div class="metric"><b>Anchor set</b><span>Stable longitudinal comparison.</span></div><div class="metric"><b>Raw evidence</b><span>Logs, checks, timings, tool counts.</span></div></div></div><details open><summary>What not to compare</summary><div>Do not compare one-off public-dev runs as official model rankings. Do not compare runs with different tool access, credentials, reasoning settings, or timeout policies without labeling them.</div></details><details><summary>How hidden checks work</summary><div>Public task specs describe the grading shape. Private/fresh packs can add hidden checks so agents cannot pass by memorizing public expected strings.</div></details></div></section>`;}
function result(){const r=state.result;const cats=Object.entries(r.category_scores||{}).sort((a,b)=>a[0].localeCompare(b[0])).slice(0,18);const tasks=(r.tasks||[]).slice(0,8);return `<section class="section"><div class="section-head"><span class="pill">Run detail</span><h1>${esc(r.run_id)}</h1><p class="lead">${esc(modelName(r))} · ${esc(r.agent)} · ${esc(r.suite)} · ${r.official?'official':'unofficial sample'}</p></div><div class="result-card"><div class="scoreline"><span class="big">${pct(r.overall_score)}</span><span class="small">overall · raw ${pct(r.raw_overall_score)}</span></div><div class="metrics"><div class="metric"><b>${num(r.passed_task_count)} / ${num(r.task_count)}</b><span>passed</span></div><div class="metric"><b>${pct(r.false_done_rate)}</b><span>false done</span></div><div class="metric"><b>${pct(r.timeout_rate)}</b><span>timeout</span></div><div class="metric"><b>${pct(r.verification_compliance)}</b><span>verification</span></div><div class="metric"><b>${seconds(r.median_wall_time_seconds)}</b><span>median task</span></div><div class="metric"><b>${num(r.total_tokens)}</b><span>tokens</span></div></div></div><section class="section split"><div class="card"><h2>Category scores</h2><div class="bars">${cats.map(([k,v])=>`<div class="barrow"><label>${esc(k)}</label><span>${pct(v)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,Number(v)*100))}%"></i></div></div>`).join('')}</div></div><div class="card"><h2>Task evidence sample</h2>${tasks.map(t=>`<details><summary>${esc(t.task_id)} · ${pct(t.score)}</summary><div>${esc(t.status)} · false_done=${Boolean(t.false_done)} · timeout=${Boolean(t.timeout)} · tools=${num(t.tool_calls)}</div></details>`).join('')}</div></section></section>`;}
function submit(){return `<section class="section"><div class="section-head"><span class="pill">Run locally</span><h1>Submit evidence, not vibes.</h1><p class="lead">The public suite works without external credentials. Upload endpoints are scaffolding; official runs remain maintainer-controlled.</p></div><div class="split"><div class="code"><code>uv run hermesbench validate-tasks\nuv run hermesbench run --agent hermes --suite public-dev --output-dir results/my-run\nuv run hermesbench score results/my-run/*.json\nuv run hermesbench upload results/my-run/*.json</code></div><div class="card"><h2>Submission status</h2><p class="muted">Public uploads are unofficial by default. Official results require private/fresh packs, run manifests, score hashes, and archived raw evidence.</p><div class="chips"><a class="chip" href="https://github.com/riceharvest/hermesbench/blob/main/docs/api.md">API docs</a><a class="chip" href="https://github.com/riceharvest/hermesbench/blob/main/docs/official-runs.md">Official policy</a><a class="chip" href="https://github.com/riceharvest/hermesbench/blob/main/docs/methodology.md">Methodology</a></div></div></div></section>`;}
function docs(){return `<section class="section"><div class="section-head"><span class="pill">Docs hub</span><h1>Keep the site scannable. Keep depth in GitHub.</h1></div><div class="task-groups">${['methodology.md','official-runs.md','api.md','architecture.md','provenance.md','deployment-website.md'].map(f=>`<a class="task-card" href="https://github.com/riceharvest/hermesbench/blob/main/docs/${f}"><h3>${f}</h3><p class="muted">Open source documentation →</p></a>`).join('')}</div></section>`;}
function render(){const path=(location.hash.replace('#','')||'/').replace(/\/$/,'')||'/';updateNav(path);const app=document.getElementById('app');const map={'/':home,'/leaderboard':leaderboard,'/tasks':tasks,'/methodology':methodology,'/runs/latest':result,'/submit':submit,'/docs':docs};app.innerHTML=(map[path]||home)();wire();}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});const f=document.getElementById('f'),s=document.getElementById('s'),sort=document.getElementById('sort');if(f)f.oninput=e=>{state.filter=e.target.value;render();};if(s)s.onchange=e=>{state.suite=e.target.value;render();};if(sort)sort.onchange=e=>{state.sort=e.target.value;render();};}
nav();Promise.all([loadJson('data/leaderboard.json'),loadJson('data/latest-result.json')]).then(([leader,result])=>{state.leader=leader;state.result=result;render();addEventListener('hashchange',render);}).catch(err=>{document.getElementById('app').innerHTML=`<section class="card"><h1>Unable to load data</h1><p class="muted">${esc(err.message)}</p></section>`;});
