async function loadJson(path){const r=await fetch(path);if(!r.ok)throw new Error(path);return r.json();}
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const pct=(x,d=0)=>x==null?'—':`${(Number(x)*100).toFixed(d)}%`;
const num=(x,d=0)=>x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const compact=x=>x==null?'—':Number(x).toLocaleString(undefined,{notation:'compact',maximumFractionDigits:2});
const seconds=x=>x==null?'—':`${Number(x).toFixed(Number(x)<10?1:0)}s`;
const modelName=e=>[e.provider,e.model].filter(Boolean).join('/')+(e.reasoning_effort?` · ${e.reasoning_effort}`:'');
const routes=[['/','Why'],['/leaderboard','Results'],['/tasks','Tasks'],['/methodology','Scoring'],['/submit','Run']];
const taskStats={total:80,publicDev:55,longHorizon:10,categories:['reading files','editing files','running tests','fixing bugs','writing summaries','checking issues','researching docs','troubleshooting settings','using a browser','analyzing CSV files','reading logs','checking security reports','improving Docker files','debugging CI failures','scheduling jobs','recovering context','respecting memory/privacy boundaries','drafting email/calendar replies','using a local mock API','catching false done claims']};
const suiteCards=[['short reliability','public-dev','55','Quick local tasks. Good for checking whether an agent can use tools without getting lost.'],['long-horizon endurance','long-horizon-dev','10','Longer staged tasks. Good for checking whether an agent keeps working until the evidence is real.'],['anchor set','anchor','5','A small stable set kept around so old and new runs can be compared over time.'],['fresh waves','fresh-rolling','5','New tasks added over time so models cannot simply memorize the benchmark.'],['private holdout','private-holdout','5','Hidden official tasks used by maintainers for cleaner public rankings.']];
let state={leader:null,run:null,filter:'',suite:'',sort:'score',view:'cards'};
function sourceRows(l){return(l.official||[]).length||(l.unofficial||[]).length?[...(l.official||[]),...(l.unofficial||[])]:[...(l.entries||[])];}
function dedupe(rows){const seen=new Set();return rows.filter(e=>{const k=e.run_id||`${e.provider}/${e.model}/${e.suite}/${e.reasoning_effort}`;if(seen.has(k))return false;seen.add(k);return true;});}
function summaries(l){if((l.model_summaries||[]).length)return l.model_summaries;return dedupe(sourceRows(l)).map(e=>({...e,submission_count:1,best_score_percentage:e.score_percentage??e.overall_score,average_score_percentage:e.score_percentage??e.overall_score,best_submission_id:e.run_id}));}
function scoreOf(e){return e.score_percentage??e.overall_score??e.average_score_percentage??e.best_score_percentage??0}
function rawOf(e){return e.raw_overall_score??e.raw_score_percentage??e.best_raw_score_percentage??scoreOf(e)}
function reliability(e){return e.reliability_score??Math.max(0,1-(((e.false_done_rate??e.average_false_done_rate??0)*.65)+((e.timeout_rate??e.average_timeout_rate??0)*.35)))}
function tokenEff(e){const t=e.total_tokens??e.average_total_tokens;return e.token_efficiency_score??(scoreOf(e)&&t?scoreOf(e)/t*1e6:null)}
function rows(){const q=state.filter.toLowerCase();return dedupe(sourceRows(state.leader)).filter(e=>{const hay=[e.run_id,e.agent,e.provider,e.model,e.suite,e.reasoning_effort].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state.suite||e.suite===state.suite)}).sort((a,b)=>{if(state.sort==='reliability')return reliability(b)-reliability(a);if(state.sort==='speed')return(a.median_wall_time_seconds??Infinity)-(b.median_wall_time_seconds??Infinity);if(state.sort==='tokens')return(tokenEff(b)??-1)-(tokenEff(a)??-1);if(state.sort==='raw')return rawOf(b)-rawOf(a);return scoreOf(b)-scoreOf(a)});}
function nav(){for(const id of ['desktop-nav','bottom-nav']){const el=document.getElementById(id);if(el)el.innerHTML=routes.map(([href,label])=>`<a href="#${href}" data-route="${href}">${label}</a>`).join('')}}
function updateNav(path){document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===path));}
function pageIntro(kicker,title,body){return `<section class="page-intro"><span class="kicker">${esc(kicker)}</span><h1>${esc(title)}</h1><p>${esc(body)}</p></section>`}
function fold(title,body,open=false){return `<details ${open?'open':''}><summary>${esc(title)}</summary><div class="fold-body">${body}</div></details>`}
function metric(label,value,sub=''){return `<div class="metric"><b>${value}</b><span>${esc(label)}</span>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function home(){const runs=dedupe(sourceRows(state.leader));return `${pageIntro('Plain English','Can the agent actually finish the job?','HermesBench gives an AI agent a real task, then checks the files, commands, logs, and test results. It rewards proof, not confident wording.')}
<section class="focus-card primary-focus"><h2>One simple rule</h2><p>If an agent says “done,” HermesBench asks: where is the working artifact and did the checks pass?</p><a class="btn primary" href="#/leaderboard">See current results</a></section>
<section class="single-list">
${metric('tasks and templates',num(80),'small and long tasks')}
${metric('short reliability tasks',num(55),'quick local checks')}
${metric('long endurance tasks',num(10),'multi-step work')}
${metric('committed runs',num(runs.length),'sample results')}
</section>
${fold('Why not just use normal AI benchmarks?',`<p>Many popular benchmarks are static question sets. Models can train on similar examples or learn the style. That makes scores look better than real-life performance.</p><p>HermesBench uses work that must be executed: read files, change files, run checks, and leave evidence.</p>`)}
${fold('Are these official rankings?',`<p>No. The public runs here are useful samples. Official rankings should use private and fresh task packs so models cannot memorize the exact tasks.</p>`)}
<section class="cta-strip"><span>Want the details?</span><a href="#/methodology">Read how scoring works</a></section>`}
function controls(){const suites=[...new Set(sourceRows(state.leader).map(e=>e.suite).filter(Boolean))].sort();return `<section class="controls"><label>Find a model<input id="f" type="search" value="${esc(state.filter)}" placeholder="deepseek, gpt, mistral"></label><label>Task set<select id="s"><option value="">All task sets</option>${suites.map(x=>`<option ${state.suite===x?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>Sort by<select id="sort">${[['score','Best score'],['reliability','Most reliable'],['speed','Fastest'],['tokens','Best token use'],['raw','Raw score']].map(([v,l])=>`<option ${state.sort===v?'selected':''} value="${v}">${l}</option>`).join('')}</select></label></section>`}
function resultCard(e,i){const model=[e.provider,e.model].filter(Boolean).join('/')||'unknown model',passed=e.best_passed_task_count??e.passed_task_count,taskCount=e.best_task_count??e.task_count,failed=e.best_failed_task_count??e.failed_task_count,fdCount=e.best_false_done_count??e.false_done_count,fd=e.average_false_done_rate??e.false_done_rate,toCount=e.best_timeout_count??e.timeout_count,to=e.average_timeout_rate??e.timeout_rate,time=e.best_median_wall_time_seconds??e.median_wall_time_seconds,tokens=e.average_total_tokens??e.total_tokens,tools=e.average_tool_call_count??e.tool_call_count;return `<article class="result-card"><div class="rank-row"><span class="rank-badge">#${i+1}</span><span>${e.official?'official':'sample'}</span></div><h2>${esc(model)}</h2><p>${esc(e.agent||'agent')} · ${esc(e.suite||'task set')} · ${esc(e.reasoning_effort||'no reasoning label')}</p><div class="score-row"><b>${pct(scoreOf(e))}</b><span>${num(passed)}/${num(taskCount)} tasks passed</span></div><div class="result-numbers">${metric('tasks failed',num(failed))}${metric('false done',`${num(fdCount)} · ${pct(fd)}`)}${metric('timeouts',`${num(toCount)} · ${pct(to)}`)}${metric('typical task time',seconds(time))}${metric('tokens used',compact(tokens))}${metric('tool calls',num(tools))}</div>${fold('Audit details',`<div class="single-list compact">${metric('raw score',pct(rawOf(e)))}${metric('reliability',pct(reliability(e)))}${metric('run id',esc(e.best_submission_id||e.run_id||'—'))}${metric('tokens per passed task',compact(e.best_tokens_per_successful_task??e.tokens_per_successful_task))}</div><p><a href="#/runs/${esc(e.best_submission_id||e.run_id)}">Open the full task-by-task report</a></p>`)}<div class="card-actions"><a href="#/runs/${esc(e.best_submission_id||e.run_id)}">Task report</a><a href="#/models/${esc(e.provider||'unknown')}/${encodeURIComponent(e.model||'unknown')}">Model history</a></div></article>`}
function leaderboard(){const list=rows();return `${pageIntro('Results','Which agent run did best?','This page shows the main numbers directly. Use the fold only for audit details like raw score and run id.')}${controls()}<section class="results-grid">${list.map(resultCard).join('')}</section>${fold('What should I compare?',`<p>Start with tasks passed and false-done rate. A fast run is not useful if it skipped the work. Tokens used and tool calls help explain how much effort the run spent.</p>`)}${fold('Why are these samples?',`<p>These are public task runs from the repository. They are good for development, but official rankings should use private and fresh tasks too.</p>`)}`}
function tasks(){return `${pageIntro('Tasks','What work does the benchmark ask agents to do?','Each task is a small job with local files, expected outputs, and checks. The public tasks do not need private credentials.')}
<section class="task-groups">${suiteCards.map(([name,id,count,text])=>`<article class="task-card"><span class="rank-badge">${esc(id)}</span><h2>${esc(name)}</h2><b>${esc(count)} tasks</b><p>${esc(text)}</p></article>`).join('')}</section>
${fold('What kinds of tasks are included?',`<div class="chips">${taskStats.categories.map(c=>`<span class="chip">${esc(c)}</span>`).join('')}</div>`)}
${fold('What does a task contain?',`<p>A task includes the prompt, setup files, expected artifacts, scoring checks, cleanup notes, and metadata like difficulty and tool needs.</p>`)}`}
function methodology(){return `${pageIntro('Scoring','How does HermesBench decide what passed?','The benchmark checks evidence first. If the artifact is missing or the verifier fails, the task fails no matter how confident the final message sounded.')}
<section class="focus-card"><h2>The main score</h2><p>A run gets credit when required checks pass. The score is the share of task credit earned after penalties.</p></section>
${fold('False done penalty',`<p>“False done” means the agent claimed or implied success without enough proof. HermesBench tracks it because this is one of the most common real-world agent failures.</p>`,true)}
${fold('Reliability score',`<p>Reliability goes down when a run has false-done failures or timeouts. This helps separate careful agents from agents that only look fast.</p>`)}
${fold('Public, fresh, and private tasks',`<p>Public tasks help developers iterate. Fresh waves reduce memorization. Private holdout tasks are for cleaner official comparisons.</p>`)}
${fold('What not to compare',`<p>Do not treat one public sample as a final model ranking. Compare task set, reasoning setting, tool access, cost, time, and whether the run used hidden or public tasks.</p>`)}`}
function checksList(t){return (t.checks||[]).slice(0,80).map(c=>`<li class="${c.status==='pass'?'good':c.status==='fail'?'bad':''}"><b>${esc(c.status)}</b> ${esc(c.label)}</li>`).join('')}
function taskList(tasks){return `<section class="task-breakdown">${tasks.map(t=>{const status=t.timeout?'timeout':t.false_done?'false done':t.passed?'passed':'failed';return `<details><summary><span class="status ${status==='passed'?'ok':'no'}">${esc(status)}</span>${esc(t.task_id)} · ${pct(t.score)}</summary><div class="fold-body"><div class="single-list compact">${metric('time',seconds(t.wall_time_seconds))}${metric('tool calls',num(t.tool_calls))}${metric('tokens',num((t.token_usage||{}).total_tokens))}${metric('category',esc(t.category||'—'))}</div><ul class="checks">${checksList(t)}</ul></div></details>`}).join('')}</section>`}
async function runDetail(id){if(!state.run||state.run.run_id!==id)state.run=await loadJson(`data/runs/${id}.json`);const r=state.run;return `${pageIntro('Task report',`Run ${r.run_id}`,`${modelName(r)}. This page focuses on whether every task passed.`)}<section class="focus-card"><div class="score-row"><b>${pct(r.overall_score)}</b><span>${num(r.passed_task_count)}/${num(r.task_count)} tasks passed</span></div><div class="single-list compact">${metric('false done',`${num(r.false_done_count)} · ${pct(r.false_done_rate)}`)}${metric('timeouts',`${num(r.timeout_count)} · ${pct(r.timeout_rate)}`)}${metric('typical task time',seconds(r.median_wall_time_seconds))}${metric('tokens',num(r.total_tokens))}</div></section>${fold('Show every task',taskList(r.tasks||[]),true)}`}
function modelPage(provider,model){model=decodeURIComponent(model||'');const list=sourceRows(state.leader).filter(e=>(e.provider||'unknown')===provider&&(e.model||'unknown')===model);return `${pageIntro('Model history',model,`Runs for provider ${provider}.`)}<section class="results-grid">${dedupe(list).map(resultCard).join('')}</section>`}
function submit(){return `${pageIntro('Run locally','Try the benchmark on your own agent','The public tasks are designed to run on a normal machine without private accounts.')}
<section class="focus-card"><h2>Quick start</h2><pre><code>uv run hermesbench validate-tasks
uv run hermesbench run --agent hermes --suite public-dev --output-dir results/my-run
uv run hermesbench score results/my-run/*.json</code></pre></section>
${fold('What happens when I run it?',`<p>The runner creates a temporary folder, copies task fixtures, starts the agent, waits for the result, runs checks, and writes a JSON report.</p>`)}
${fold('Can I submit a result?',`<p>The upload flow is scaffolded. Public uploads should be treated as unofficial until maintainers verify the run settings and evidence.</p>`)}`}
async function render(){const raw=(location.hash.replace('#','')||'/').replace(/\/$/,'')||'/',parts=raw.split('/').filter(Boolean),path=parts[0]?`/${parts[0]}`:'/';updateNav(path);const app=document.getElementById('app');try{if(path==='/runs'&&parts[1])app.innerHTML=await runDetail(parts[1]);else if(path==='/models')app.innerHTML=modelPage(parts[1]||'unknown',parts.slice(2).join('/'));else app.innerHTML=({'/':home,'/leaderboard':leaderboard,'/tasks':tasks,'/methodology':methodology,'/submit':submit}[path]||home)();wire()}catch(e){app.innerHTML=`<section class="focus-card"><h1>Could not load this page</h1><p>${esc(e.message)}</p></section>`}}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});const f=document.getElementById('f'),s=document.getElementById('s'),sort=document.getElementById('sort');if(f)f.oninput=e=>{state.filter=e.target.value;render()};if(s)s.onchange=e=>{state.suite=e.target.value;render()};if(sort)sort.onchange=e=>{state.sort=e.target.value;render()}}
nav();Promise.all([loadJson('data/leaderboard.json'),loadJson('data/latest-result.json')]).then(([leader])=>{state.leader=leader;render();addEventListener('hashchange',render)}).catch(err=>{document.getElementById('app').innerHTML=`<section class="focus-card"><h1>Could not load data</h1><p>${esc(err.message)}</p></section>`});
