async function loadJson(path){const r=await fetch(path); if(!r.ok) throw new Error(path); return r.json();}
function pct(x){return `${Math.round((x||0)*100)}%`;}
function num(x,d=0){return x==null?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});}
function money(x){return x==null?'—':`$${Number(x).toFixed(x<1?4:2)}`;}
function seconds(x){return x==null?'—':`${Number(x).toFixed(1)}s`;}
const categories=['file operations','codebase navigation','bugfixes','issue triage','docs research','provider config','browser automation','CSV/data','logs','CVE triage','Docker/CI','cron','context recovery','memory boundary','email/calendar','mock APIs','false-done traps','cost/latency'];
const taskList=document.querySelector('#task-list');
if(taskList){categories.forEach(c=>{const div=document.createElement('div'); div.className='task-chip'; div.textContent=c; taskList.appendChild(div);});}
Promise.all([loadJson('data/leaderboard.json'),loadJson('data/latest-result.json')]).then(([leader,result])=>{
 const body=document.querySelector('#leaderboard-table tbody');
 const render=(rows,label)=>{rows.forEach(e=>{const tr=document.createElement('tr'); const model=[e.provider,e.model].filter(Boolean).join('/')+(e.reasoning_effort?` · reasoning ${e.reasoning_effort}`:''); const cls=e.official?`${label} #${e.rank}`:'Unofficial sample'; tr.innerHTML=`<td>${cls}</td><td><strong>${e.agent}</strong></td><td>${model}</td><td class="score">${pct(e.score_percentage??e.overall_score)}</td><td>${pct(e.pass_at_1)}</td><td class="${e.false_done_rate ? 'bad' : ''}">${pct(e.false_done_rate)}</td><td>${pct(e.timeout_rate)}</td><td>${seconds(e.total_execution_time_seconds)}</td><td>${money(e.total_cost_usd??e.cost_usd)}</td><td>${e.score_per_dollar==null?'—':num(e.score_per_dollar,1)}</td><td>${num(e.total_tokens)}</td><td>${num(e.tool_call_count)}</td><td>${e.official?'Official hidden/private repeated run':'Single public-dev run; not ranked'}</td>`; body.appendChild(tr);});};
 render(leader.official||[],'Official'); render(leader.unofficial||[],'Unofficial');
 if(!(leader.official||[]).length){const tr=document.createElement('tr'); tr.innerHTML='<td colspan="13" class="muted">No official private/fresh-pack runs have been published yet.</td>'; body.prepend(tr);}
 const detail=document.querySelector('#result-detail');
 const metricCards=[['Total score',`${num(result.total_score,2)} / ${num(result.max_score)}`],['Raw score',pct(result.raw_overall_score)],['Total time',seconds(result.total_execution_time_seconds)],['Median task time',seconds(result.median_wall_time_seconds)],['P95 task time',seconds(result.p95_wall_time_seconds)],['Tool calls',num(result.tool_call_count)],['Avg tools/task',num(result.avg_tool_calls_per_task,1)],['Total tokens',num(result.total_tokens)],['Input tokens',num(result.input_tokens)],['Output tokens',num(result.output_tokens)],['Cost',money(result.total_cost_usd??result.cost_usd)],['Value',result.score_per_dollar==null?'—':num(result.score_per_dollar,1)]].map(([k,v])=>`<div class="mini"><strong>${k}</strong><br><span class="score">${v}</span></div>`).join('');
 const cats=Object.entries(result.category_scores||{}).slice(0,12).map(([k,v])=>`<div class="mini"><strong>${k}</strong><br><span class="score">${pct(v)}</span></div>`).join('');
 const tasks=(result.tasks||[]).slice(0,6).map(t=>`<div class="mini"><strong>${t.task_id}</strong><br>${t.status} · score ${pct(t.score)}<br><span class="muted">false_done=${t.false_done}; timeout=${t.timeout}; tool_calls=${t.tool_calls}</span></div>`).join('');
 const modelLine=[result.provider,result.model].filter(Boolean).join('/')+(result.reasoning_effort?` · reasoning ${result.reasoning_effort}`:'');
 detail.innerHTML=`<p><span class="pill">${result.official?'Official':'Unofficial demo'}</span> <strong>${result.run_id}</strong> — ${modelLine} — <span class="score">overall ${pct(result.overall_score)}</span></p><div class="result-grid">${metricCards}</div><h3 style="margin-top:22px">Category scores</h3><div class="result-grid">${cats}</div><h3 style="margin-top:22px">Task evidence sample</h3><div class="result-grid">${tasks}</div>`;
}).catch(err=>{document.querySelector('#result-detail').textContent='Unable to load demo data: '+err.message;});
